###
POST http://192.168.178.12:4003/verify_signature
Content-Type:application/json

{
  "credential" : "HC1:NCFOXN%TSMAHN-H+XSN-7D$AUJKAIU099C$E 43G-VC9B5G2Q7HI9C.H94.OQWOQHIZC4TPIFRMLNKNM8JI0EUG*%NH$RSC92GF8DTE1KO87J4F8FU:4RETF10UB/9BL5C2F$KU8VHO0VQK96VP8BS41E3NNM78R-H9NTBY4Z7W99WD2IZD5CC9G%89-8CNNF54DABYYMAHLW 70SO:GOLIROGO3T5ZXK W5WGKZ/MPS4V77GQ0 EQPCR8U6XHQNSPO+Q*ERVH5*XKMB43Q4IOR3/RN95*28-W7AC5ADN.-O8L6IWMW KAHA508XIORW6%5L+L8NR7*.4$HMDYA 96CX8LCNEAOWP4BD7WJ8+YMHBQ:YM/D7JSPZHQ1CQEPPXKRM.QDNQL*OXQ6CJP.NR:SQKSON64-ZOHZ5-HQM47TKRTEHGAREG3RA3/43KD3O13P-JQ20BNCPX81R69O6IR9/NN$MPV*OH*OTHQGSOBIR*ER8JP.96SC5 76FR7 POOOGJ O--3.UBB9S31GMDPDSP+7G%/2RL3DE4:$JE JXVU%JBJMC:/00CL82D.LE:3CQ7U7R5GH2GGP605-VOH7T:TGK.V%2LI0RIFJ6XJNJN"
}


###
POST http://192.168.178.12:4003/verify_signature
Content-Type:application/json

{
  "credential" : "HC1:NCF7X3W08$$Q030:+HGHBFO026M6M4NHSU5S8CUHC9:R7YL8YW7.6JUVM0$U7UQ%-B/$5X$59498$BLQH*CT4TJ603TRTIHKK5H6%EJTEPTSIWEJFAYMPRMQ%BOPUGIL3P2CHZMZ35D:2G7JU5E0B180OZ0W7:O/C5TAVVO5X$D+BTE$C:EWP 1Z$29%IDM5-6Q+F56U0ZBI0*8UEADP2LBLM9QH7HWPIYMGCXA5773R7 HFOV0-VG::AP9POXD6-J/WM4*R*O7HZSJG3NYTLQFT5D51V 4C5D8M-JOYLNTC*%MG5LWI1 H7%DNGUQ%3RQ$H4DQULL905%*1ZV6S9GIUHL103BHVUVZU9 0I%:DVF1H21LCCLCB$W4HVN%2BN7CLK07BG/PS:W3$M91WI5N02 QASQNY81+6BJ9OFERUK-AHWU5I7L-%2ZY9J/G:-A/UFGIIETL6 G41W00JIRP-NMJLP.W7 7BHJ0J V%%HR/HMWQG+CVX9NQABH8129 G6KD38L4I6G$6WT.73ZR80WH+582DUZ1O3G.9NGWNTZJ*.6NCVLUR0IH2SLH.SMPU 0PL:MDAOENSYUIJ9NH9OK8BZ6S:38IME6OE*QVUSR1FW+:QU0"
}

